apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-container
  template:
    metadata:
      labels:
        app: ml-container
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: ml-container
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-container
spec:
  ports:
  - port: 6379
  selector:
    app: ml-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-process
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: batch-process
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: batch-process
        image: microsoft/batch-process:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: REDIS
          value: "ml-container"
---
apiVersion: v1
kind: Service
metadata:
  name: batch-process
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: batch-process