apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-container
  template:
    metadata:
      labels:
        app: ml-container
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: ml-container
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
